"""initial schema

Revision ID: db16edb6d298
Revises:
Create Date: 2026-09-05 03:41:03.626604
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "db16edb6d298"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chains",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("code", sa.Enum("TRON", "ETHEREUM", name="chain_code"), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("explorer_url_template", sa.String(length=255), nullable=False),
        sa.Column("address_format", sa.String(length=32), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chains")),
        sa.UniqueConstraint("code", name=op.f("uq_chains_code")),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "EXCHANGE",
                "MIXER",
                "BRIDGE",
                "TOKEN_CONTRACT",
                "DEFI",
                "GAMBLING",
                "SANCTIONED",
                "MERCHANT",
                "UNKNOWN",
                name="entity_type",
            ),
            nullable=False,
        ),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("jurisdiction", sa.String(length=100), nullable=True),
        sa.Column("is_fiu_ind_registered", sa.Boolean(), nullable=True),
        sa.Column("is_sanctioned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("contact_channel", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
    )
    op.create_index(op.f("ix_entities_name"), "entities", ["name"], unique=False)
    op.create_table(
        "label_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("licence", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "reliability",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="label_reliability"),
            nullable=False,
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dataset_date", sa.Date(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label_sources")),
        sa.UniqueConstraint("name", name=op.f("uq_label_sources_name")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "INVESTIGATOR", "ANALYST", "VIEWER", name="user_role"),
            nullable=False,
        ),
        sa.Column("organisation", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.SmallInteger(), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("is_contract", sa.Boolean(), nullable=True),
        sa.Column("first_seen_block", sa.BigInteger(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.id"], name=op.f("fk_addresses_chain_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
        sa.UniqueConstraint("chain_id", "address", name="chain_id_address"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.SmallInteger(), nullable=False),
        sa.Column("contract_address", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("decimals", sa.SmallInteger(), nullable=True),
        sa.Column("is_native", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_stablecoin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.id"], name=op.f("fk_assets_chain_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("chain_id", "contract_address", name="chain_id_contract_address"),
    )
    op.create_index(
        "ix_assets_native_unique",
        "assets",
        ["chain_id"],
        unique=True,
        postgresql_where=sa.text("is_native"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("payload_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_audit_log_actor_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_case_created", "audit_log", ["case_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_log_request_id"), "audit_log", ["request_id"], unique=False)
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_number", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("ncrp_reference", sa.String(length=64), nullable=True),
        sa.Column("fir_reference", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reported_loss_inr", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("incident_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "ANALYSING", "REVIEW", "CLOSED", name="case_status"),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="priority"),
            server_default="MEDIUM",
            nullable=False,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_cases_owner_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index(op.f("ix_cases_case_number"), "cases", ["case_number"], unique=True)
    op.create_index(op.f("ix_cases_fir_reference"), "cases", ["fir_reference"], unique=False)
    op.create_index(op.f("ix_cases_ncrp_reference"), "cases", ["ncrp_reference"], unique=False)
    op.create_index(op.f("ix_cases_owner_id"), "cases", ["owner_id"], unique=False)
    op.create_index(
        "ix_cases_owner_status_created", "cases", ["owner_id", "status", "created_at"], unique=False
    )
    op.create_table(
        "address_labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("label_source_id", sa.Integer(), nullable=False),
        sa.Column("label_text", sa.String(length=300), nullable=False),
        sa.Column("label_type", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_address_labels_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_address_labels_entity_id")
        ),
        sa.ForeignKeyConstraint(
            ["label_source_id"],
            ["label_sources.id"],
            name=op.f("fk_address_labels_label_source_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_address_labels")),
        sa.UniqueConstraint(
            "address_id",
            "label_source_id",
            "label_text",
            name="address_id_label_source_id_label_text",
        ),
    )
    op.create_index("ix_address_labels_address_id", "address_labels", ["address_id"], unique=False)
    op.create_table(
        "address_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("data_version", sa.BigInteger(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tx_count_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tx_count_out", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unique_counterparties_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unique_counterparties_out", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_in_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("total_out_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("balance_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("age_days", sa.Integer(), nullable=True),
        sa.Column("active_days", sa.Integer(), nullable=True),
        sa.Column("median_dwell_seconds", sa.BigInteger(), nullable=True),
        sa.Column("sweep_ratio", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("distinct_assets", sa.Integer(), nullable=True),
        sa.Column(
            "features", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_address_profiles_address_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_address_profiles")),
        sa.UniqueConstraint("address_id", "data_version", name="address_id_data_version"),
    )
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("root_address_id", sa.Integer(), nullable=False),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "PARTIAL",
                "FAILED",
                "CANCELLED",
                name="analysis_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "RETRIEVAL",
                "NORMALIZATION",
                "ENRICHMENT",
                "TRACING",
                "GRAPH",
                "PATTERNS",
                "ATTRIBUTION",
                "RISK",
                "ALERTS",
                name="analysis_stage",
            ),
            nullable=True,
        ),
        sa.Column("progress_pct", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "degradations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "engine_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_analysis_runs_case_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["root_address_id"], ["addresses.id"], name=op.f("fk_analysis_runs_root_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"], ["users.id"], name=op.f("fk_analysis_runs_triggered_by")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
    )
    op.create_index(op.f("ix_analysis_runs_case_id"), "analysis_runs", ["case_id"], unique=False)
    op.create_table(
        "case_addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SUSPECT", "VICTIM_SOURCE", "DISCOVERED", name="address_role"),
            nullable=False,
        ),
        sa.Column("reported_amount_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("reported_asset_id", sa.Integer(), nullable=True),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anchor_tx_hash", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("added_by", sa.Integer(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["added_by"], ["users.id"], name=op.f("fk_case_addresses_added_by")
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_case_addresses_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_addresses_case_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reported_asset_id"], ["assets.id"], name=op.f("fk_case_addresses_reported_asset_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_addresses")),
        sa.UniqueConstraint("case_id", "address_id", "role", name="case_id_address_id_role"),
    )
    op.create_index("ix_case_addresses_address_id", "case_addresses", ["address_id"], unique=False)
    op.create_table(
        "case_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_assignments_case_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_case_assignments_user_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_assignments")),
        sa.UniqueConstraint("case_id", "user_id", name="case_id_user_id"),
    )
    op.create_index(
        op.f("ix_case_assignments_case_id"), "case_assignments", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_assignments_user_id"), "case_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "case_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("pinned_finding_type", sa.String(length=64), nullable=True),
        sa.Column("pinned_finding_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_case_notes_author_id")),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_notes_case_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_notes")),
    )
    op.create_index(op.f("ix_case_notes_case_id"), "case_notes", ["case_id"], unique=False)
    op.create_table(
        "case_timeline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_case_timeline_actor_id")),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_timeline_case_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_timeline")),
    )
    op.create_index(op.f("ix_case_timeline_case_id"), "case_timeline", ["case_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chain_id", sa.SmallInteger(), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("from_address_id", sa.Integer(), nullable=False),
        sa.Column("to_address_id", sa.Integer(), nullable=True),
        sa.Column("fee_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "FAILED", "REVERTED", "PENDING", name="transfer_status"),
            nullable=False,
        ),
        sa.Column("nonce", sa.BigInteger(), nullable=True),
        sa.Column("input_size", sa.Integer(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.id"], name=op.f("fk_transactions_chain_id")),
        sa.ForeignKeyConstraint(
            ["from_address_id"], ["addresses.id"], name=op.f("fk_transactions_from_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["to_address_id"], ["addresses.id"], name=op.f("fk_transactions_to_address_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("chain_id", "tx_hash", name="chain_id_tx_hash"),
    )
    op.create_index(
        op.f("ix_transactions_block_time"), "transactions", ["block_time"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "alert_type",
            sa.Enum(
                "SANCTIONED_CONTACT",
                "MIXER_CONTACT",
                "CRITICAL_RISK",
                "CROSS_CASE_MATCH",
                name="alert_type",
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.Enum("LOW", "MEDIUM", "HIGH", name="severity"), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("trigger_reason", sa.Text(), nullable=False),
        sa.Column("source_finding_type", sa.String(length=64), nullable=True),
        sa.Column("source_finding_id", sa.String(length=64), nullable=True),
        sa.Column("acknowledged_by", sa.Integer(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"], ["users.id"], name=op.f("fk_alerts_acknowledged_by")
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_alerts_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_alerts_analysis_run_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_alerts_case_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        "ix_alerts_open",
        "alerts",
        ["case_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("acknowledged_at IS NULL"),
    )
    op.create_table(
        "attributions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "EXCHANGE",
                "MIXER",
                "BRIDGE",
                "TOKEN_CONTRACT",
                "DEFI",
                "GAMBLING",
                "SANCTIONED",
                "MERCHANT",
                "UNKNOWN",
                name="entity_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "tier",
            sa.Enum("CONFIRMED", "PROBABLE", "UNATTRIBUTED", name="attribution_tier"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column(
            "method",
            sa.Enum(
                "DATASET_MATCH",
                "DEPOSIT_HEURISTIC",
                "CLASSIFIER",
                "MANUAL",
                name="attribution_method",
            ),
            nullable=False,
        ),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "( tier = 'CONFIRMED' AND entity_id IS NOT NULL AND confidence IS NULL AND jsonb_typeof(evidence) = 'array' AND jsonb_array_length(evidence) > 0) OR ( tier = 'PROBABLE' AND confidence IS NOT NULL AND confidence > 0 AND confidence <= 1 AND jsonb_typeof(evidence) = 'array' AND jsonb_array_length(evidence) > 0) OR ( tier = 'UNATTRIBUTED' AND entity_id IS NULL AND confidence IS NULL)",
            name=op.f("ck_attributions_tier_requires_evidence"),
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_attributions_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_attributions_analysis_run_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_attributions_entity_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attributions")),
    )
    op.create_index(
        "ix_attributions_address_computed",
        "attributions",
        ["address_id", "computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attributions_analysis_run_id"), "attributions", ["analysis_run_id"], unique=False
    )
    op.create_table(
        "evidence_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "evidence_type",
            sa.Enum("API_RESPONSE", "REPORT", "GRAPH_IMAGE", name="evidence_type"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("endpoint", sa.String(length=500), nullable=True),
        sa.Column(
            "request_params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_fixture", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_evidence_items_analysis_run_id"),
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_evidence_items_case_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
    )
    op.create_index(op.f("ix_evidence_items_case_id"), "evidence_items", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_items_content_sha256"), "evidence_items", ["content_sha256"], unique=False
    )
    op.create_table(
        "pattern_findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "pattern_type",
            sa.Enum(
                "FAN_OUT",
                "FAN_IN",
                "RAPID_TRANSFER",
                "PEEL_CHAIN",
                "DORMANCY_BURST",
                "STRUCTURING",
                name="pattern_type",
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.Enum("LOW", "MEDIUM", "HIGH", name="severity"), nullable=False),
        sa.Column("subject_address_id", sa.Integer(), nullable=False),
        sa.Column(
            "involved_address_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "trigger_tx_hashes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("false_positive_note", sa.Text(), nullable=False),
        sa.Column("detector_version", sa.String(length=32), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_pattern_findings_analysis_run_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_address_id"],
            ["addresses.id"],
            name=op.f("fk_pattern_findings_subject_address_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pattern_findings")),
    )
    op.create_index(
        op.f("ix_pattern_findings_analysis_run_id"),
        "pattern_findings",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=True),
        sa.Column("report_type", sa.Enum("FULL", "SUMMARY", name="report_type"), nullable=False),
        sa.Column("format", sa.Enum("PDF", "JSON", "CSV", name="report_format"), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("generated_by", sa.Integer(), nullable=False),
        sa.Column(
            "narrative_source", sa.Enum("TEMPLATE", "LLM", name="narrative_source"), nullable=False
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"], ["analysis_runs.id"], name=op.f("fk_reports_analysis_run_id")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_reports_case_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name=op.f("fk_reports_generated_by")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_case_id"), "reports", ["case_id"], unique=False)
    op.create_table(
        "risk_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column(
            "band", sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="risk_band"), nullable=False
        ),
        sa.Column("confidence", sa.Numeric(precision=18, scale=12), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "not_evaluated",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(signals) = 'array' AND jsonb_array_length(signals) > 0",
            name=op.f("ck_risk_assessments_signals_not_empty"),
        ),
        sa.CheckConstraint(
            "confidence > 0 AND confidence <= 1", name=op.f("ck_risk_assessments_confidence_range")
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 100", name=op.f("ck_risk_assessments_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_risk_assessments_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_risk_assessments_analysis_run_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_assessments")),
        sa.UniqueConstraint("analysis_run_id", "address_id", name="analysis_run_id_address_id"),
    )
    op.create_table(
        "traces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("root_address_id", sa.Integer(), nullable=False),
        sa.Column(
            "direction", sa.Enum("FORWARD", "BACKWARD", name="trace_direction"), nullable=False
        ),
        sa.Column("anchor_tx_hash", sa.String(length=128), nullable=True),
        sa.Column("max_depth", sa.SmallInteger(), nullable=False),
        sa.Column("taint_threshold", sa.Numeric(precision=18, scale=12), nullable=False),
        sa.Column("edge_budget", sa.Integer(), nullable=False),
        sa.Column("taint_model", sa.Enum("HAIRCUT", name="taint_model"), nullable=False),
        sa.Column("node_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("edge_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_traced_raw", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_traces_analysis_run_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["root_address_id"], ["addresses.id"], name=op.f("fk_traces_root_address_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traces")),
    )
    op.create_index(op.f("ix_traces_analysis_run_id"), "traces", ["analysis_run_id"], unique=False)
    op.create_table(
        "transfers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column("chain_id", sa.SmallInteger(), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=False),
        sa.Column("transfer_index", sa.Integer(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("from_address_id", sa.Integer(), nullable=False),
        sa.Column("to_address_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("amount_raw", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("decimals", sa.SmallInteger(), nullable=True),
        sa.Column("usd_value_approx", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "FAILED", "REVERTED", "PENDING", name="transfer_status"),
            nullable=False,
        ),
        sa.Column("is_internal", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], name=op.f("fk_transfers_asset_id")),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.id"], name=op.f("fk_transfers_chain_id")),
        sa.ForeignKeyConstraint(
            ["from_address_id"], ["addresses.id"], name=op.f("fk_transfers_from_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["to_address_id"], ["addresses.id"], name=op.f("fk_transfers_to_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], name=op.f("fk_transfers_transaction_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfers")),
        sa.UniqueConstraint(
            "chain_id", "tx_hash", "transfer_index", name="chain_id_tx_hash_transfer_index"
        ),
    )
    op.create_index("ix_transfers_chain_hash", "transfers", ["chain_id", "tx_hash"], unique=False)
    op.create_index(
        "ix_transfers_from_time", "transfers", ["from_address_id", "block_time"], unique=False
    )
    op.create_index(
        "ix_transfers_pair_time",
        "transfers",
        ["from_address_id", "to_address_id", "block_time"],
        unique=False,
    )
    op.create_index(
        "ix_transfers_to_time", "transfers", ["to_address_id", "block_time"], unique=False
    )
    op.create_table(
        "attribution_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attribution_id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "override_tier",
            sa.Enum("CONFIRMED", "PROBABLE", "UNATTRIBUTED", name="attribution_tier"),
            nullable=False,
        ),
        sa.Column("override_entity_id", sa.Integer(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_attribution_overrides_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["attribution_id"],
            ["attributions.id"],
            name=op.f("fk_attribution_overrides_attribution_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["override_entity_id"],
            ["entities.id"],
            name=op.f("fk_attribution_overrides_override_entity_id"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_attribution_overrides_user_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribution_overrides")),
    )
    op.create_table(
        "trace_edges",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("trace_id", sa.Integer(), nullable=False),
        sa.Column("from_address_id", sa.Integer(), nullable=False),
        sa.Column("to_address_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("total_amount_raw", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("tainted_amount_raw", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("transfer_count", sa.Integer(), nullable=False),
        sa.Column("first_transfer_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_transfer_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "tx_hashes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], name=op.f("fk_trace_edges_asset_id")),
        sa.ForeignKeyConstraint(
            ["from_address_id"], ["addresses.id"], name=op.f("fk_trace_edges_from_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["to_address_id"], ["addresses.id"], name=op.f("fk_trace_edges_to_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"], ["traces.id"], name=op.f("fk_trace_edges_trace_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trace_edges")),
        sa.UniqueConstraint(
            "trace_id",
            "from_address_id",
            "to_address_id",
            "asset_id",
            name="trace_id_from_address_id_to_address_id_asset_id",
        ),
    )
    op.create_index("ix_trace_edges_trace_id", "trace_edges", ["trace_id"], unique=False)
    op.create_table(
        "trace_nodes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("trace_id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("depth", sa.SmallInteger(), nullable=False),
        sa.Column("taint_share", sa.Numeric(precision=18, scale=12), nullable=False),
        sa.Column("tainted_amount_raw", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("is_terminal", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "termination_reason",
            sa.Enum(
                "MAX_DEPTH",
                "BELOW_THRESHOLD",
                "SERVICE_BOUNDARY",
                "NO_OUTFLOW",
                "EDGE_BUDGET",
                "TIME_WINDOW",
                name="termination_reason",
            ),
            nullable=True,
        ),
        sa.Column("first_reached_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_trace_nodes_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"], ["traces.id"], name=op.f("fk_trace_nodes_trace_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trace_nodes")),
        sa.UniqueConstraint("trace_id", "address_id", name="trace_id_address_id"),
    )
    op.create_index(
        "ix_trace_nodes_trace_depth", "trace_nodes", ["trace_id", "depth"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trace_nodes_trace_depth", table_name="trace_nodes")
    op.drop_table("trace_nodes")
    op.drop_index("ix_trace_edges_trace_id", table_name="trace_edges")
    op.drop_table("trace_edges")
    op.drop_table("attribution_overrides")
    op.drop_index("ix_transfers_to_time", table_name="transfers")
    op.drop_index("ix_transfers_pair_time", table_name="transfers")
    op.drop_index("ix_transfers_from_time", table_name="transfers")
    op.drop_index("ix_transfers_chain_hash", table_name="transfers")
    op.drop_table("transfers")
    op.drop_index(op.f("ix_traces_analysis_run_id"), table_name="traces")
    op.drop_table("traces")
    op.drop_table("risk_assessments")
    op.drop_index(op.f("ix_reports_case_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_pattern_findings_analysis_run_id"), table_name="pattern_findings")
    op.drop_table("pattern_findings")
    op.drop_index(op.f("ix_evidence_items_content_sha256"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_case_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_attributions_analysis_run_id"), table_name="attributions")
    op.drop_index("ix_attributions_address_computed", table_name="attributions")
    op.drop_table("attributions")
    op.drop_index(
        "ix_alerts_open", table_name="alerts", postgresql_where=sa.text("acknowledged_at IS NULL")
    )
    op.drop_table("alerts")
    op.drop_index(op.f("ix_transactions_block_time"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_case_timeline_case_id"), table_name="case_timeline")
    op.drop_table("case_timeline")
    op.drop_index(op.f("ix_case_notes_case_id"), table_name="case_notes")
    op.drop_table("case_notes")
    op.drop_index(op.f("ix_case_assignments_user_id"), table_name="case_assignments")
    op.drop_index(op.f("ix_case_assignments_case_id"), table_name="case_assignments")
    op.drop_table("case_assignments")
    op.drop_index("ix_case_addresses_address_id", table_name="case_addresses")
    op.drop_table("case_addresses")
    op.drop_index(op.f("ix_analysis_runs_case_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_table("address_profiles")
    op.drop_index("ix_address_labels_address_id", table_name="address_labels")
    op.drop_table("address_labels")
    op.drop_index("ix_cases_owner_status_created", table_name="cases")
    op.drop_index(op.f("ix_cases_owner_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_ncrp_reference"), table_name="cases")
    op.drop_index(op.f("ix_cases_fir_reference"), table_name="cases")
    op.drop_index(op.f("ix_cases_case_number"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_audit_log_request_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_case_created", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(
        "ix_assets_native_unique", table_name="assets", postgresql_where=sa.text("is_native")
    )
    op.drop_table("assets")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("label_sources")
    op.drop_index(op.f("ix_entities_name"), table_name="entities")
    op.drop_table("entities")
    op.drop_table("chains")
    # ### end Alembic commands ###
